version: "3.8"

services:
  postgres:
    container_name: node-nest-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: node-nest

  cache:
    container_name: node-nest-redis
    image: redis
    ports:
      - "6379:6379"